name: intro to ci
on: 
  push: 

jobs: 
  hello-world:
    runs-on: ubuntu-latest


    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: bun install 

      - name: Install dependencies
        run : bun install

      - name: Build
        run : bun run build

  

